services:
  postgres-mock:
    image: debezium/postgres
    container_name: vivo-synq_postgres-mock
    networks:
      - vivo-synq_network
    env_file:
      - ./env/mock.env
    ports:
      - 5432:5432
    volumes:
      - ./database/mock_dump.sql:/docker-entrypoint-initdb.d/mock_dump.sql
      - ./database/mock_dump_insert.sql:/tmp/mock_dump_insert.sql
      - ./database/mock_dump_test.sql:/tmp/mock_dump_test.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: vivo-synq_zookeeper
    networks:
      - vivo-synq_network
    ports:
      - 2181:2181
    env_file:
      - ./env/zookeeper.env

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: vivo-synq_kafka
    networks:
      - vivo-synq_network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - ./env/kafka.env

  kafka-exporter:
    image: danielqsj/kafka-exporter:latest
    container_name: dashboard-kafka-exporter
    ports:
      - "9308:9308"
    environment:
      - KAFKA_BROKERS=kafka://kafka:9092
    depends_on:
      - kafka
    networks:
      - vivo-synq_network

  connector:
    image: debezium/connect:latest
    container_name: vivo-synq_connector
    networks:
      - vivo-synq_network
    ports:
      - "8083:8083"
    env_file:
      - ./env/debezium.env
    depends_on:
      - zookeeper
      - kafka

  redis-cache:
    image: redis:latest
    container_name: vivo-synq_redis-cache
    volumes:
      - ./database/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - vivo-synq_network
    ports:
      - 6379:6379
    env_file:
      - ./env/redis.env

  redis-exporter:
    image: bitnami/redis-exporter:latest
    container_name: dashboard-redis-exporter
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis://redis-cache:6379
    depends_on:
      - redis-cache
    networks:
      - vivo-synq_network

  # consumer:
  #   container_name: vivo-synq_consumer
  #   build:
  #     context: ./consumer
  #     dockerfile: Dockerfile
  #   env_file:
  #     - ./env/consumer.env
  #   networks:
  #     - vivo-synq_network
  #   depends_on:
  #     - postgres-mock
  #     - zookeeper
  #     - kafka
  #     - connector
  #     - redis-cache
  #     - redis-exporter

  api:
    container_name: vivo-synq_api
    build:
      context: ./api
      dockerfile: Dockerfile
    # ports:
    #   - "8080:8080"
    expose: [8080]
    env_file:
      - ./env/api.env
    networks:
      - vivo-synq_network
    depends_on:
      - redis-cache
      - redis-exporter

  nginx:
    image: nginx:latest
    container_name: vivo-synq_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /var/cache/nginx:/var/cache/nginx
    networks:
      - vivo-synq_network
    depends_on:
      - api

networks:
  vivo-synq_network:
    name: vivo-synq_network
    driver: bridge
