services:
  postgres-mock:
    image: debezium/postgres
    container_name: vivo-synq_postgres-mock
    networks:
      - kafka-network
    env_file:
      - ./env/mock.env
    ports:
      - 5432:5432
    volumes:
      - ./database/mock_schema.sql:/docker-entrypoint-initdb.d/mock_schema.sql

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: vivo-synq_zookeeper
    networks:
      - kafka-network
    ports:
      - 2181:2181
    env_file:
      - ./env/zookeeper.env

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: vivo-synq_kafka
    networks:
      - kafka-network
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    env_file:
      - ./env/kafka.env

  connector:
    image: debezium/connect:latest
    container_name: vivo-synq_connector
    networks:
      - kafka-network
    ports:
      - "8083:8083"
    env_file:
      - ./env/debezium.env
    depends_on:
      - zookeeper
      - kafka

networks:
  kafka-network:
    name: vivo-synq_kafka-network
    driver: bridge
