version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_vivo_mock
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpw
      MYSQL_DATABASE: mock_vivo
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysecretpw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  nifi:
    image: apache/nifi:latest
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      NIFI_WEB_HTTP_PORT: 8080
    volumes:
      - nifi_data:/opt/nifi/nifi-current/logs
    depends_on:
      - mysql

volumes:
  mysql_data:
  nifi_data:
