services:
  mysql:
    image: mysql:latest
    container_name: mysql_vivo_mock
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vivo_mock
      - MYSQL_USER=vivo
      - MYSQL_PASSWORD=vivo
    ports:
      - "3306:3306"
    networks:
      - default
    volumes:
      - mysql_data:/var/lib/mysql

  nifi:
    build:
      context: ./nifi
    image: apache/nifi:latest
    container_name: nifi_etl
    ports:
      - "8443:8443"
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=nifi
      - SINGLE_USER_CREDENTIALS_PASSWORD=nifi
      - TZ=America/Sao_Paulo
    networks:
      - default
    volumes:
      - nifi_data:/opt/nifi/nifi-current/logs
    depends_on:
      - mysql

networks:
  default:
    driver: bridge

volumes:
  mysql_data:
  nifi_data:
