/*
 * Products
 *
 * Retorna os dados de posse de produtos de um cliente.  # Definições Está api retorna os produtos contratados de um cliente. Na Vivo existem várias opções de produtos, dentre eles se destacam, a telefonia móvel 5G, a internet de fibra, a TV por assinatura, produtos de casa inteligente e muitos outros produtos de parceiros, como netflix, amazon prime, que podem ser contratados como um pacote pelo cliente.      https://www.vivo.com.br/
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package entity

// Informação detalhada do produto.
type Description struct {
	// Texto com informações descritivas do produto.
	Text string `json:"text"`
	// HTTPS URL
	Url string `json:"url,omitempty"`
	// Category of the description. This field is used to
	// provide further info about displaying of the
	// description text:  - 'general': Descrição comercial
	// do produto, intruções de uso, dentre outras informações.
	// - 'dates': inforções sobre prazo de contratação e duração
	// do produto.  - 'promotion': Descrição sobre a promoção do produto.
	Category string `json:"category,omitempty"`
}
