/*
 * Products
 *
 * Retorna os dados de posse de produtos de um cliente.  # Definições Está api retorna os produtos contratados de um cliente. Na Vivo existem várias opções de produtos, dentre eles se destacam, a telefonia móvel 5G, a internet de fibra, a TV por assinatura, produtos de casa inteligente e muitos outros produtos de parceiros, como netflix, amazon prime, que podem ser contratados como um pacote pelo cliente.      https://www.vivo.com.br/
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package entity

// Informações sobre o preço pago pelo cliente no produto.
type Price struct {
	// Descritivo do preço.
	Description string `json:"description"`
	// Type of the price. - 'recurring' Preço cobrado recorrentemente,
	// podendo ser de diversas formas, como diário, semanal, mensal, etc.
	// - 'usage' preço pago por consumo, como por exemplo 100gb de internet
	// por R$ 100. - 'one-shot' Pago apenas uma vez.
	Type string `json:"type"`
	// Período de cobrança recorrente.
	RecurringPeriod string `json:"recurring_period,omitempty"`

	Amount *PriceAmount `json:"amount"`
}
