{
 "title": "VivoSynq",
 "description": "Dashboard MongoDB Atlas Vivo Synq",
 "time": { "from": "2024-10-02T19:16:15.889Z", "to": "2024-10-02T19:26:15.889Z" },
 "panels": [
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_uptimeMillis{job=\"mongodb-atlas\"})/(3000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_network_numRequests{job=\"mongodb-atlas\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache ",
   "type": "stat",
   "description": "\nA quantidade total de dados armazenados atualmente no cache.",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_bytes_currently_in_the_cache{group_id=\"66d0d0d90623836d876bcc0a\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registros atualizados/dia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_history_store_table_updates_without_timestamps_fixed_up_by_reinserting_with_the_fixed_timestamp)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_exporter_last_scrape_duration_seconds{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões na última hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "mongodb_connections_current{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saúde Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Espaço Usado",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_disk_metrics_disk_space_used_bytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espaço Livre",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_disk_metrics_disk_space_free_bytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM utilizada",
   "type": "stat",
   "description": "Uma estimativa de quanta memória está disponível para iniciar novos aplicativos, sem troca.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "2780000 - hardware_system_memory_mem_available_kilobytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM disponível",
   "type": "stat",
   "description": "Uma estimativa de quanta memória está disponível para iniciar novos aplicativos, sem troca.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_system_memory_mem_available_kilobytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Processo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(hardware_process_cpu_kernel_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(hardware_process_cpu_user_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Sistema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(hardware_system_cpu_kernel_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])/10",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(hardware_system_cpu_user_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])/10",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 28 },
   "options": {
    "content": "![kafka logo](https://miro.medium.com/v2/resize:fit:702/1*D0Xk8hmBB3zuyhGl1TDu3A.png)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 28 },
   "options": {
    "content": "![redis logo](https://download.logo.wine/logo/Redis/Redis-Logo.wine.png)"
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 28 },
   "options": {
    "content": "![mongodb logo](https://1000logos.net/wp-content/uploads/2020/08/MongoDB-Logo.png)"
   }
  },
  {
   "title": "Kafka",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"kafka-exporter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"redis-exporter:9121\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Cluster 1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"cluster0-shard-00-00.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Cluster 2",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Kafka Brokers ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_brokers{instance=\"kafka-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Redis Scrape Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redis_target_scrape_request_errors_total{instance=\"redis-exporter:9121\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MongoDB Cluster 3",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"cluster0-shard-00-02.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}