{
 "title": "VivoSynqa",
 "description": "Dashboard MongoDB Atlas Vivo Synq",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "Registros atualizados/dia",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_history_store_table_updates_without_timestamps_fixed_up_by_reinserting_with_the_fixed_timestamp)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache (GBs)",
   "type": "stat",
   "description": "\nA quantidade total de dados armazenados atualmente no cache.",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_bytes_currently_in_the_cache) / 1073741824",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_connections_current{group_id=\"66d0d0d90623836d876bcc0a\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}