{
 "title": "VivoSynq",
 "description": "Dashboard MongoDB Atlas Vivo Synq",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_uptimeMillis{job=\"mongodb-atlas\"})/(3000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total de requisições",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(mongodb_network_numRequests{job=\"mongodb-atlas\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache ",
   "type": "stat",
   "description": "\nA quantidade total de dados armazenados atualmente no cache.",
   "gridPos": { "h": 4, "w": 6, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_bytes_currently_in_the_cache{group_id=\"66d0d0d90623836d876bcc0a\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registros atualizados/dia",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(mongodb_wiredTiger_cache_history_store_table_updates_without_timestamps_fixed_up_by_reinserting_with_the_fixed_timestamp)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo de resposta",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "redis_exporter_last_scrape_duration_seconds{job=\"redis\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Conexões na última hora",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "mongodb_connections_current{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Saúde Hardware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Espaço Usado",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_disk_metrics_disk_space_used_bytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Espaço Livre",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_disk_metrics_disk_space_free_bytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM utilizada",
   "type": "stat",
   "description": "Uma estimativa de quanta memória está disponível para iniciar novos aplicativos, sem troca.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "2780000 - hardware_system_memory_mem_available_kilobytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memória RAM disponível",
   "type": "stat",
   "description": "Uma estimativa de quanta memória está disponível para iniciar novos aplicativos, sem troca.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "hardware_system_memory_mem_available_kilobytes{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Processo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(hardware_process_cpu_kernel_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(hardware_process_cpu_user_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "CPU Sistema",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(hardware_system_cpu_kernel_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])/10",
     "legendFormat": "{{label_name}}"
    },
    {
     "expr": "rate(hardware_system_cpu_user_milliseconds{instance=\"cluster0-shard-00-01.2aci7.mongodb.net:27018\"}[$__rate_interval])/10",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}